<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="119" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="119" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
      <class name="extentReports.NewTest1">
        <test-method status="PASS" signature="TC1()[pri:0, instance:extentReports.NewTest1@4e718207]" name="TC1" duration-ms="4" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest1@4e718207]" name="getResult" is-config="true" duration-ms="1" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC1 status=SUCCESS method=NewTest1.TC1()[pri:0, instance:extentReports.NewTest1@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC2()[pri:0, instance:extentReports.NewTest1@4e718207]" name="TC2" duration-ms="2" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest1@4e718207]" name="getResult" is-config="true" duration-ms="1" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC2 status=SUCCESS method=NewTest1.TC2()[pri:0, instance:extentReports.NewTest1@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TC3()[pri:0, instance:extentReports.NewTest1@4e718207]" name="TC3" duration-ms="2" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC3 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest1@4e718207]" name="getResult" is-config="true" duration-ms="0" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC3 status=SUCCESS method=NewTest1.TC3()[pri:0, instance:extentReports.NewTest1@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- extentReports.NewTest1 -->
      <class name="extentReports.NewTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:extentReports.NewTest@32eebfca]" name="setUp" is-config="true" duration-ms="247" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="functionality2Test1()[pri:0, instance:extentReports.NewTest@32eebfca]" name="functionality2Test1" duration-ms="14" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality2Test1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest@32eebfca]" name="getResult" is-config="true" duration-ms="12" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality2Test1 status=SUCCESS method=NewTest.functionality2Test1()[pri:0, instance:extentReports.NewTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="functionality2Test2()[pri:0, instance:extentReports.NewTest@32eebfca]" name="functionality2Test2" duration-ms="26" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sakinala] but found [Krishna]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sakinala] but found [Krishna]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at extentReports.NewTest.functionality2Test2(NewTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality2Test2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest@32eebfca]" name="getResult" is-config="true" duration-ms="9" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality2Test2 status=FAILURE method=NewTest.functionality2Test2()[pri:0, instance:extentReports.NewTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="functionality2Test3()[pri:0, instance:extentReports.NewTest@32eebfca]" name="functionality2Test3" duration-ms="2" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at org.testng.Assert.assertNotEquals(Assert.java:1162)
at extentReports.NewTest.functionality2Test3(NewTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality2Test3 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest@32eebfca]" name="getResult" is-config="true" duration-ms="2" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality2Test3 status=FAILURE method=NewTest.functionality2Test3()[pri:0, instance:extentReports.NewTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:extentReports.NewTest@32eebfca]" name="tearDown" is-config="true" duration-ms="370" started-at="2019-02-06T13:42:17Z" finished-at="2019-02-06T13:42:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReports.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
